# https://scrutinizer-ci.com/docs/configuration
checks:
  python:
    code_rating: true
    duplicate_code: true

filter:
  excluded_paths:
    - setup.py
    - .setup/*
    - Examples/*
    - Tests/*

tools:
  external_code_coverage:
    timeout: 1200
    runs: 6