# scrutinizer-ci.com configurations
# https://scrutinizer-ci.com/docs/configuration
# https://scrutinizer-ci.com/docs/guides/python/continuous-integration-deployment
checks:
  python:
    code_rating: true
    duplicate_code: true

filter:
  excluded_paths:
    - setup.py
    - .setup/*
    - Examples/*
    - Tests/*

tools:
  external_code_coverage:
    timeout: 120
    runs: 6

before_commands:
    - bash Tests/install.sh

build:
  tests:
    override:
      - bash Tests/run.sh 

